### ISSUE TITLE
Is the Chinese model for simplified han script or traditional?

### ISSUE THREAD

**Issue by tkurosaka** [abzif/babzel#5]
This is just a question.
Is the model listed as Chinese for Simplified (script) Chinese, Traditional Chinese, or support both?

**Comment by abzif** [comment]
According to description on UnivDependencies some texts are in traditional chinese, some texts are in simplified chinese. The model is trained on all the text, so theoretically it should support both. However tokenization "performance" is about 90% so it is not very impressive. OpenNLP seems not be very good for far-east languages (or maybe annotated texts size is too small to train a good model).
